// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Data;

#nullable disable

namespace WebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425235026_AddAllTables")]
    partial class AddAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "clients-1.webp"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "clients-2.webp"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "clients-3.webp"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "clients-4.webp"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "clients-5.webp"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "clients-6.webp"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Web Design"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Branding"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Icon = "bi bi-bounding-box-circles icon",
                            Title = "Feature 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Icon = "bi bi-calendar4-week icon",
                            Title = "Feature 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Icon = "bi bi-broadcast icon",
                            Title = "Feature 3"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Client = "Client A",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ProjectDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectUrl = "Project A",
                            Title = "App 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Client = "Client B",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ProjectDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectUrl = "Project B",
                            Title = "App 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Client = "Client C",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ProjectDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectUrl = "Project C",
                            Title = "App 3"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.PortfolioImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "portfolio-10.webp",
                            PortfolioId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "portfolio-2.webp",
                            PortfolioId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "portfolio-2.webp",
                            PortfolioId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "portfolio-3.webp",
                            PortfolioId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "portfolio-5.webp",
                            PortfolioId = 3
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "portfolio-6.webp",
                            PortfolioId = 3
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident",
                            Icon = "bi bi-brightness-high",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            Icon = "bi bi-calendar4-week",
                            Title = "Sed ut perspiciatis"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
                            Icon = "bi bi-binoculars",
                            Title = "Magni Dolores"
                        },
                        new
                        {
                            Id = 4,
                            Description = "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque",
                            Icon = "bi bi-bar-chart",
                            Title = "Nemo Enim"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Quis consequatur saepe eligendi voluptatem consequatur dolor consequuntur",
                            Icon = "bi bi-card-checklist",
                            Title = "Dele cardo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Modi nostrum vel laborum. Porro fugit error sit minus sapiente sit asperiores",
                            Icon = "bi bi-binoculars",
                            Title = "Divera don"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonLink = "#",
                            ButtonText = "Learn More",
                            ImageUrl = "hero-carousel-1.jpg",
                            SubTitle = "Hero carousel slide 1",
                            Title = "Slider 1"
                        },
                        new
                        {
                            Id = 2,
                            ButtonLink = "#",
                            ButtonText = "Learn More",
                            ImageUrl = "hero-carousel-2.jpg",
                            SubTitle = "Hero carousel slide 2",
                            Title = "Slider 2"
                        },
                        new
                        {
                            Id = 3,
                            ButtonLink = "#",
                            ButtonText = "Learn More",
                            ImageUrl = "hero-carousel-3.jpg",
                            SubTitle = "Hero carousel slide 3",
                            Title = "Slider 3"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Portfolio", b =>
                {
                    b.HasOne("WebApplication.Models.Category", "Category")
                        .WithMany("Portfolios")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication.Models.PortfolioImage", b =>
                {
                    b.HasOne("WebApplication.Models.Portfolio", "Portfolio")
                        .WithMany("PortfolioImages")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("WebApplication.Models.Category", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("WebApplication.Models.Portfolio", b =>
                {
                    b.Navigation("PortfolioImages");
                });
#pragma warning restore 612, 618
        }
    }
}
